# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/git@github.com:johnsinco/prompt-engineering.git',
                'doc_host': 'https://johnsinco.github.io',
                'git_url': 'https://github.com/johnsinco/git@github.com:johnsinco/prompt-engineering.git',
                'lib_path': 'git@github.com:johnsinco/prompt_engineering.git'},
  'syms': {'prompt_engineering.git.core': {'prompt_engineering.git.core.foo': ('core.html#foo', 'prompt_engineering.git/core.py')}}}
